In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('/Users/catalinabernal/Desktop/Quantil/criteria/Libro Esther/GenAI-Science/data/prompts.csv')
df.head()

                                              prompt
0  I want to write an article about: "Common fair...
1  I want to write an article about: "Machine Lea...
2  I want to write an article about: "Evaluation ...
3  I want to write an article about: "Benchmark c...
4  I want to write an article about: "Word embedd...

In [3]:
df.shape

(2135, 1)

In [4]:
df_mel = df.sample(n=10, random_state=42)
df_cat = df.sample(n=10, random_state=24)

In [9]:
df_mel.sort_index().to_csv('../data/revision_manual/df_mel.csv', index=False)
df_cat.sort_index().to_csv('../data/revision_manual/df_cat.csv', index=False)

In [8]:
df_cat.sort_index()

                                                 prompt
98    I want to write an article about: "Heavy relia...
126   I want to write an article about: "The same mo...
664   What is the current consensus on the statement...
815   What is the current consensus on the statement...
1198  Write a short literature review on the stateme...
1593  Evaluate the strength of evidence across the f...
1617  Evaluate the strength of evidence across the f...
1852  Evaluating the body of evidence on the stateme...
2104  Define "Few-shot prompting ". Include references.
2133  Define "Extrinsic hallucinations". Include ref...

In [ ]:
df_mel.sort_index()

                                                 prompt
70    I want to write an article about: "Standard co...
231   Explain the following statement: "Workers may ...
297   Explain the following statement: "Adolescents ...
298   Explain the following statement: "Adolescents ...
719   What is the current consensus on the statement...
1429  Sources pro or against the statement "Data poi...
1483  Evaluate the strength of evidence across the f...
1837  Evaluating the body of evidence on the stateme...
2019  I'm analyzing this article https://www.science...
2053  I'm analyzing this article https://wjarr.com/s...