In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('../data/revision_manual/df_cat.csv')
df.head(2)

                                              prompt
0  I want to write an article about: "Heavy relia...
1  I want to write an article about: "The same mo...

In [28]:
## gemini
df_gemini = pd.read_csv('../data/analisis/results_gemini_links.csv')
df_mistral = pd.read_csv('../data/results/results_mistral.csv')

## GPT

In [3]:
df_gpt1 = pd.read_csv('../data/results/results_gpt.csv')
df_gpt2 = pd.read_csv('../data/results/results_gpt_web_search_V2.csv')

In [4]:
df_gpt1.head(2)

,prompt,result,references,tokens
0,"I want to write an article about: ""Common fair...",Several studies demonstrate the mathematical i...,['https://jmlr.org/beta/papers/v24/22-1511.htm...,NaN
1,"I want to write an article about: ""Machine Lea...",Machine learning models can exhibit bias even ...,['https://www.forbes.com/sites/aparnadhinakara...,NaN

In [5]:
df_gpt2.head(2)

,prompt,result,references,tokens
0,"Explain the following statement: ""Common fairn...","The statement ""Common fairness definitions are...",['https://algorithmaudit.eu/knowledge-platform...,NaN
1,"Explain the following statement: ""Machine Lear...",Machine learning models can exhibit bias even ...,['https://www.forbes.com/sites/aparnadhinakara...,NaN

In [63]:
prompt = df['prompt'].iloc[7]
print(prompt)

Evaluating the body of evidence on the statement "Feeding the algorithm with socially cued (network-salient) search terms can weaken reinforcement and may reduce affective polarization". Summarize areas of agreement and disagreement and identify unresolved questions.

In [64]:
df_gpt1[df_gpt1['prompt'] == prompt]

,prompt,result,references,tokens
1852,Evaluating the body of evidence on the stateme...,### Summary of Evidence on Socially Cued Searc...,[],NaN

In [65]:
df_gpt2[df_gpt2['prompt'] == prompt]

,prompt,result,references,tokens
964,Evaluating the body of evidence on the stateme...,Feeding algorithms with socially cued (network...,['https://knowledge.uchicago.edu/record/14793/...,NaN

In [66]:
print(df_gpt2[df_gpt2['prompt'] == prompt]['references'].iloc[0])

['https://knowledge.uchicago.edu/record/14793/files/leung-urminsky-2025-the-narrow-search-effect-and-how-broadening-search-promotes-belief-updating.pdf?utm_source=openai', 'https://arxiv.org/abs/2411.14652?utm_source=openai', 'https://arxiv.org/abs/2403.17286?utm_source=openai', 'https://link.springer.com/article/10.3758/s13415-018-0635-z?utm_source=openai', 'https://link.springer.com/article/10.3758/s13414-010-0001-x?utm_source=openai', 'https://pubmed.ncbi.nlm.nih.gov/29040279/?utm_source=openai', 'https://pmc.ncbi.nlm.nih.gov/articles/PMC10898967/?utm_source=openai', 'https://www.cambridge.org/core/journals/american-political-science-review/article/polarizing-effect-of-partisan-echo-chambers/5044B63A13A458A97CA747E9DCA07228?utm_source=openai', 'https://www.cambridge.org/core/journals/political-science-research-and-methods/article/affective-polarization-and-coalition-signals/5B128D1C86C07E126075E460B893DE4D?utm_source=openai', 'https://academic.oup.com/jcmc/article/27/6/zmac018/6700671?utm_source=openai', 'https://academic.oup.com/ijpor/article/36/3/edae042/7731557?utm_source=openai', 'https://academic.oup.com/poq/article/87/4/911/7471689?utm_source=openai', 'https://www.frontiersin.org/journals/psychology/articles/10.3389/fpsyg.2014.00649/full?utm_source=openai', 'https://polarization-research-lab.github.io/library/posts/65/?utm_source=openai', 'https://polarization-research-lab.github.io/library/posts/67/?utm_source=openai']

In [67]:
print(df_gemini[df_gemini['prompt'] == prompt]['references_real'].iloc[0])

["Error: MissingSchema: Invalid URL '': No scheme supplied. Perhaps you meant https://?"]

In [68]:
print(df_mistral[df_mistral['prompt'] == prompt]['references'].iloc[0])

['[1] Pariser, E. (2011). The Filter Bubble: What the Internet Is Hiding from You. Penguin Books.\n', '[2] Flaxman, S., Goel, T., & Rao, N. (2016). Estimating the causal effects of news consumption and fact-checking on political beliefs. Proceedings of the National Academy of Sciences, 113(49), 13749-13754.\n', '[3] Iyengar, S., & Westwood, S. (2015). Is less more? A field experiment on the effects of exposure to opposing political advertisements. Proceedings of the National Academy of Sciences, 112(3), 782-787.\n', '[4] Sunstein, C. R. (2017). #Rep']