In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('../data/revision_manual/df_cat.csv')
df.head(2)

                                              prompt
0  I want to write an article about: "Heavy relia...
1  I want to write an article about: "The same mo...

In [28]:
## gemini
df_gemini = pd.read_csv('../data/analisis/results_gemini_links.csv')
df_mistral = pd.read_csv('../data/results/results_mistral.csv')

## GPT

In [3]:
df_gpt1 = pd.read_csv('../data/results/results_gpt.csv')
df_gpt2 = pd.read_csv('../data/results/results_gpt_web_search_V2.csv')

In [4]:
df_gpt1.head(2)

,prompt,result,references,tokens
0,"I want to write an article about: ""Common fair...",Several studies demonstrate the mathematical i...,['https://jmlr.org/beta/papers/v24/22-1511.htm...,NaN
1,"I want to write an article about: ""Machine Lea...",Machine learning models can exhibit bias even ...,['https://www.forbes.com/sites/aparnadhinakara...,NaN

In [5]:
df_gpt2.head(2)

,prompt,result,references,tokens
0,"Explain the following statement: ""Common fairn...","The statement ""Common fairness definitions are...",['https://algorithmaudit.eu/knowledge-platform...,NaN
1,"Explain the following statement: ""Machine Lear...",Machine learning models can exhibit bias even ...,['https://www.forbes.com/sites/aparnadhinakara...,NaN

In [44]:
prompt = df['prompt'].iloc[4]
print(prompt)

Write a short literature review on the statement "Clearer distinctions between security interests and privacy interests can improve how AI developers and institutions explain AI systems to users". Include references.

In [45]:
df_gpt1[df_gpt1['prompt'] == prompt]

,prompt,result,references,tokens
1198,Write a short literature review on the stateme...,### Literature Review\n\nThe intersection of s...,[],NaN

In [46]:
df_gpt2[df_gpt2['prompt'] == prompt]

,prompt,result,references,tokens
522,Write a short literature review on the stateme...,Clear distinctions between security and privac...,['https://arxiv.org/abs/2312.01555?utm_source=...,NaN

In [48]:
print(df_gpt2[df_gpt2['prompt'] == prompt]['references'].iloc[0])

['https://arxiv.org/abs/2312.01555?utm_source=openai', 'https://www.tandfonline.com/doi/abs/10.1080/10447318.2025.2606953?utm_source=openai', 'https://www.brookings.edu/articles/making-ai-more-explainable-to-protect-the-public-from-individual-and-community-harms/?utm_source=openai', 'https://laweconcenter.org/resources/the-trust-constraint-on-personalized-ai-how-transparency-and-adaptive-governance-can-unlock-ai-productivity/?utm_source=openai', 'https://www.tandfonline.com/doi/full/10.1080/08839514.2025.2463722?utm_source=openai', 'https://www.frontiersin.org/journals/artificial-intelligence/articles/10.3389/frai.2022.826737/full?utm_source=openai', 'https://aaronhall.com/legal-risks-in-ai-systems-without-transparent-data-use/?utm_source=openai', 'https://iapp.org/news/a/privacy-and-responsible-ai?utm_source=openai', 'https://www.indwes.edu/articles/2025/12/responsible-ai-you-can-defend-privacy-bias-transparency-governance.html?utm_source=openai', 'https://link.springer.com/article/10.1007/s10207-024-00813-3?utm_source=openai', 'https://www.trustpath.ai/blog/ai-transparency-what-it-is-and-why-it-matters-for-compliance?utm_source=openai', 'https://www.cyberly.org/en/how-does-ai-impact-privacy/index.html?utm_source=openai', 'https://www.ethicalailearning.org/lesson/lesson-5/?utm_source=openai']

In [49]:
print(df_gemini[df_gemini['prompt'] == prompt]['references_real'].iloc[0])

['https://pmc.ncbi.nlm.nih.gov/articles/PMC9044077/', 'https://www.ibm.com/think/insights/ai-privacy', 'https://verasafe.com/blog/what-are-the-privacy-concerns-with-ai/', 'https://stefanini.com/en/insights/articles/ai-vs-privacy-who-holds-the-power', 'https://www.geeksforgeeks.org/artificial-intelligence/privacy-risks-in-ai-systems/', 'https://www.fortra.com/blog/ai-data-privacy-challenges-and-solutions', 'https://medium.com/@inverita/top-ai-privacy-concerns-challenges-and-solutions-5b842d5cd2cf', 'https://ovic.vic.gov.au/privacy/resources-for-organisations/artificial-intelligence-and-privacy-issues-and-challenges/', 'https://www.tredence.com/blog/ai-privacy', 'https://arxiv.org/html/2504.06552v1', 'https://witness.ai/blog/ai-privacy/']

In [50]:
print(df_mistral[df_mistral['prompt'] == prompt]['references'].iloc[0])

[]